const dbConnection = async () => {
  try {
    
  } catch (error) {
    console.log(error);
    throw new Error("Error in the - checkout logs");
  }
};
